import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import PageLayout from './components/layout/PageLayout';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.variable} h-screen w-screen cursor-default bg-background text-white antialiased`}
      >
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
