import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/toast.css'; // ✅ 추가한 CSS 파일 import 필수!

import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

import { ToastContainer } from 'react-toastify';
import PageLayout from '@/components/layout/PageLayout';
import AuthProvider from '@/provider/AuthProvider';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.variable} h-screen w-screen cursor-default bg-background text-white antialiased`}
      >
        <AuthProvider>
          <PageLayout>{children}</PageLayout>
        </AuthProvider>
        <ToastContainer
          className="custom-toast"
          position="top-right"
          autoClose={3000}
        ></ToastContainer>
      </body>
    </html>
  );
}
